// Code generated by "stringer -type=TraceType"; DO NOT EDIT.

package qabalwrap

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[EmptyTrace-0]
	_ = x[TraceStart-1]
	_ = x[TraceFinish-2]
	_ = x[TraceSpanStart-3]
	_ = x[TraceSpanFinish-4]
}

const _TraceType_name = "EmptyTraceTraceStartTraceFinishTraceSpanStartTraceSpanFinish"

var _TraceType_index = [...]uint8{0, 10, 20, 31, 45, 60}

func (i TraceType) String() string {
	if i < 0 || i >= TraceType(len(_TraceType_index)-1) {
		return "TraceType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TraceType_name[_TraceType_index[i]:_TraceType_index[i+1]]
}
